apiVersion: v2
name: brarcher
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: postgresql
    version: 14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    alias: postgresql
  - name: redis
    version: 20
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    alias: redis